import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import NumPicker from '../components/NumPicker'
// import PickColor from '../components/PickColors'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SwitchIt</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
				{/* {PickColor({name: "Background", title: "Background Color"})}
				{PickColor({name: "circleColorOne", title: "First Circle Color"})}
				{PickColor({name: "circleColortwo", title: "Second Circle Color"})}
				{PickColor({name: " firstText", title: "First Text Color"})}
				{PickColor({name: " secondText", title: "Second Text Color"})} */}
				<NumPicker />
      </main>
    </div>
  )
}
